=== edgarfariza/DAM---LENGUAJES-DE-MARCAS/Proyectos_1º/XML/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              
              <xs:element name="titulo" type="xs:string" />
              <xs:element name="autor" type="xs:string" />
              
              <xs:element name="fechaPublicacion" type="xs:gYear" />
              
              <xs:element name="editorial" type="xs:string" />
              <xs:element name="genero" type="xs:string" />
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== edgarfariza/DAM---LENGUAJES-DE-MARCAS/Proyectos_1º/XML/Entrenamientos_Basicos/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="biblioteca.xsd">

  <libro>
    <titulo>1984</titulo>
    <autor>George Orwell</autor>
    <fechaPublicacion>1949</fechaPublicacion>
    <editorial>Secker and Warburg</editorial>
    <genero>Ficción distópica</genero>
  </libro>

  <libro>
    <titulo>Don Quijote de la Mancha</titulo>
    <autor>Miguel de Cervantes</autor>
    <fechaPublicacion>1605</fechaPublicacion>
    <editorial>Francisco de Robles</editorial>
    <genero>Novela de caballerías</genero>
  </libro>

</biblioteca>
