=== edgarfariza/DAM---LENGUAJES-DE-MARCAS/Proyectos_1º/XML/clinica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="clinica">
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="paciente" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
            
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="fechaNacimiento" type="xs:date" />
              <xs:element name="direccion" type="xs:string" />
              <xs:element name="historiaClinica" type="xs:string" />
              
              <xs:element name="alergias" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="alergia" type="xs:string" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== edgarfariza/DAM---LENGUAJES-DE-MARCAS/Proyectos_1º/XML/clinica.xml
<?xml version="1.0" encoding="UTF-8"?>
<clinica 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="clinica.xsd">

  <paciente>
    <nombre>Lucia Perez</nombre>
    <fechaNacimiento>1980-05-20</fechaNacimiento>
    <direccion>Calle Alcala 23</direccion>
    <historiaClinica>Condición de salud estable, alergia al penicilina</historiaClinica>
    <alergias>
      <alergia>Penicilina</alergia>
    </alergias>
  </paciente>

  <paciente>
    <nombre>Alberto Melendez</nombre>
    <fechaNacimiento>1990-10-15</fechaNacimiento>
    <direccion>Calle Madrid 14</direccion>
    <historiaClinica>Condición de salud estable, sin alergias conocidas</historiaClinica>
  </paciente>

</clinica>
